export const Story_user_data = [
    {
      id: 1,
      avatar: "https://avatar.iran.liara.run/public/1",
      username: "Lalit kumar",
      isWatched: false,
      time: "5 days",
    },
    {
      id: 2,
      avatar: "https://avatar.iran.liara.run/public/2",
      username: "Pravesh Kumar",
      isWatched: true,
      time: "1 hr",
    },
    {
      id: 3,  
      avatar: "https://avatar.iran.liara.run/public/3",
      username: "gaurav Kumar",
      isWatched: false,
      time: "2 weeks",
    },
    {
      id: 4,
      avatar: "https://avatar.iran.liara.run/public/4",
      username: "ram Kumar",
      isWatched: true,
      time: "3 days",
    },
    {
      id: 5,
      avatar: "https://avatar.iran.liara.run/public/5",
      username: "sham Kumar",
      isWatched: false,
      time: "4 hrs",
    },
    {
      id: 6,
      avatar: "https://avatar.iran.liara.run/public/6",
      username: "mohan Kumar",
      isWatched: true,
      time: "6 days",
    },
    {
      id: 7,
      avatar: "https://avatar.iran.liara.run/public/7",
      username: "sohan Kumar",
      isWatched: false,
      time: "1 week",
    },
    {
      id: 8,
      avatar: "https://avatar.iran.liara.run/public/8",
      username: "sahil Kumar",
      isWatched: true,
      time: "2 hrs",
    },
    {
      id: 9,
      avatar: "https://avatar.iran.liara.run/public/9",
      username: "shubham Kumar",
      isWatched: false,
      time: "3 weeks",
    },
    {
      id: 10,
      avatar: "https://avatar.iran.liara.run/public/10",
      username: "sita Kumari",
      isWatched: true,
      time: "1 day",
    },
    {
      id: 11,
      avatar: "https://avatar.iran.liara.run/public/11",
      username: "sita Kumar",
      isWatched: false,
      time: "7 hrs",
    },
    {
      id: 12,
      avatar: "https://avatar.iran.liara.run/public/12",
      username: "aman Kumar",
      isWatched: true,
      time: "8 days",
    },
    {
      id: 13,
      avatar: "https://avatar.iran.liara.run/public/13",
      username: "shubham Kumar",
      isWatched: false,
      time: "9 hrs",
    },
    {
      id: 14,
      avatar: "https://avatar.iran.liara.run/public/14",
      username: "shubham Kumar",
      isWatched: true,
      time: "10 days",
    },
    {
      id: 15,
      avatar: "https://avatar.iran.liara.run/public/15",
      username: "shubham Kumar",
      isWatched: false,
      time: "11 hrs",
    },
    {
      id: 16,
      avatar: "https://avatar.iran.liara.run/public/16",
      username: "shubham Kumar",
      isWatched: true,
      time: "12 days",
    },
    {
      id: 17,
      avatar: "https://avatar.iran.liara.run/public/17",
      username: "shubham Kumar",
      isWatched: false,
      time: "13 hrs",
    },
    {
        id: 18,
        avatar: "https://avatar.iran.liara.run/public/16",
        username: "shubham Kumar",
        isWatched: false,
        time: "15 hrs",
      },
    {
      id: 19,
      avatar: "https://avatar.iran.liara.run/public/15",
      username: "shubham Kumar",
      isWatched: true,
      time: "14 days",
    },
    {
        id: 20,
        avatar: "https://avatar.iran.liara.run/public/17",
        username: "shubham Kumar",
        isWatched: true,
        time: "16 days",
      },
   
    
  ];
  